version: 1.0
provider:
  name: openfaas
  gateway: http://10.52.144.99:8080
functions:
  app:
    lang: python3
    handler: ./app
    image: devgmartino/faas-app:latest
  blockchain:
    lang: python3
    handler: ./blockchain
    image: devgmartino/faas-blockchain:latest